#!/bin/bash

cmake .. -DCMAKE_BUILD_TYPE=Debug -DCUTLASS_NVCC_ARCHS=72 -DCUTLASS_ENABLE_CUBLAS=OFF -DCUTLASS_ENABLE_CUDNN=OFF -Wno-dev -DCUDA_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CUDA_FLAGS=-O0 -DCUTLASS_LIBRARY_KERNELS=s*gemm
